#pragma once
#include <GLEW/glew.h>
#include <GLFW/glfw3.h>
#include "GLM/glm.hpp"
#include "GLM/gtc/matrix_transform.hpp"
#include <string>
#include <iostream>
#include <unordered_map>
#include <map>
#include "STB/stb_image.h"
#include <functional>